### ISSUE TITLE
FAQ bringt Error

### ISSUE THREAD

**Issue by berecont** [contao/official-demo#109] opened 2022-07-12 17:29 UTC
FAQ > How FAQs work > Fragen
Beim Anlegen und/oder Ändern einer (neuen) Frage gibt's einen Internal Server Error: Invalid jump To page: 35

**Comment by cliffparnitzky** [comment] 2022-07-12 21:46
@leofeyer This is only a probleme in the system "https://demo.contao.org/" ... The last demo code is fine.

But maybe this is also an error (`tl_faq.php line 184`) which should be fixed. What is your suggestion what we should do?

**Comment by fritzmg** [comment] 2022-07-13 07:26
If this is reproducible in a vanilla Contao instance or even in the Contao Online Demo on https://demo.contao.org/, please report it as a bug then (@berecont or @cliffparnitzky).

**Comment by berecont** [comment] 2022-07-14 08:20
just testet ... in a vanilla contao installation it works.
in the online demo it don't work
Contao 4.13.6 
php81
local installation with laragon

**Comment by fritzmg** [comment] 2022-07-14 08:35
> just testet ... in a vanilla contao installation it works.

How did you test? Are you sure you did not configure a redirect page in your FAQ archive?

**Comment by fritzmg** [comment] 2022-07-14 08:54
Yes, the issue is that the demo database references an invalid page ID in `tl_faq_category.jumpTo`. This needs to be fixed in the demo database, not in Contao.

**Comment by cliffparnitzky** [comment] 2022-07-14 09:34
It is reproducable in a vanilla contao installation:
- create a page
- define the new page as `jumpTo` for a FAQ category
- delete the new page
- enter the FAQ category and try to create a new entry

**Comment by fritzmg** [comment] 2022-07-14 09:49
@cliffparnitzky you can open an issue on `contao/contao` with that reproduction.

**Comment by leofeyer** [comment] 2022-09-01 06:40
I have fixed the demo now.

**Closed by leofeyer** 2022-09-01 06:40 UTC
